package models.auto;

import java.util.List;

import models.Person;

/**
 * Class _Company was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Company extends PlayDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String PEOPLE_PROPERTY = "people";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToPeople(Person obj) {
        addToManyTarget("people", obj, true);
    }
    public void removeFromPeople(Person obj) {
        removeToManyTarget("people", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Person> getPeople() {
        return (List<Person>)readProperty("people");
    }


}
